FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

# install compiler
RUN apt-get update
RUN apt-get -y install git wget curl unzip build-essential cmake clang

# set clang as default compiler
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100

# install OpenSSL libraries
RUn apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN apt-get -y install software-properties-common gnupg-curl
RUN apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
RUN add-apt-repository 'deb [arch=amd64,arm64,i386,ppc64el] https://mirror.serverion.com/mariadbrepo/10.5/ubuntu xenial main'
RUN apt-get update
RUN apt-get -y install libmariadbclient-dev
RUn apt-get -y install libc++-dev libc++abi-dev