FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# install tools
RUN apt-get -y install git wget curl unzip apt-transport-https ca-certificates software-properties-common gnupg-curl

# install compiler
RUN add-apt-repository ppa:savoury1/gcc-defaults-9
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade

# install compilation-tools
RUN apt-get -y install build-essential

# install cmake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
RUN apt-get update
RUN apt-get -y install cmake

# install OpenSSL libraries
RUN add-apt-repository ppa:carsten-uppenbrink-net/openssl
RUN apt-get update
RUN apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
RUN apt-get update
RUN apt-get -y install libmariadbclient-dev

RUN apt-get -y install libicu-dev

RUN echo $(cc --version)
RUN echo $(c++ --version)