FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# install tools
RUN apt-get -y install git wget curl unzip apt-transport-https ca-certificates software-properties-common gnupg-curl

# install compiler
RUN add-apt-repository universe
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh 10
RUN apt-get update

# install compilation-tools
RUN apt-get -y install build-essential

# install cmake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
RUN apt-get update
RUN apt-get -y install cmake

# set clang as default compiler
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang-10 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang-10 100

# install OpenSSL libraries
RUN apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
RUN apt-get update
RUN apt-get -y install libmariadbclient-dev
RUN apt-get -y install libc++-dev libc++abi-dev

RUN echo $(cmake --version)
RUN echo $(cc --version)
RUN echo $(c++ --version)