FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# install tools
RUN apt-get -y install git wget curl unzip apt-transport-https ca-certificates

# install compiler and compilation-tools
RUN apt-get -y install build-essential cmake 

# install OpenSSL libraries
RUn apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN apt-get -y install software-properties-common gnupg-curl
RUN RUN curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
RUN apt-get update
RUN apt-get -y install libmariadbclient-dev