FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

# install compiler
RUN apt-get update
RUN apt-get -y install git wget curl unzip build-essential cmake clang

# set clang as default compiler
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100

# install OpenSSL libraries
RUn apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN apt-get -y install software-properties-common
RUN wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
RUN echo "6528c910e9b5a6ecd3b54b50f419504ee382e4bdc87fa333a0b0fcd46ca77338 mariadb_repo_setup" \
    | sha256sum -c -
RUN chmod +x mariadb_repo_setup
RUN ./mariadb_repo_setup \
   --mariadb-server-version="mariadb-10.5"
RUN apt-get update
RUN apt-get -y install libmariadbclient-dev libmariadb-client-lgpl-dev-compat
RUn apt-get -y install libc++-dev libc++abi-dev