FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# install tools
RUN apt-get -y install git wget curl unzip apt-transport-https ca-certificates

# install compiler and compilation-tools
RUN apt-get -y install build-essential cmake clang

# set clang as default compiler
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100

# install OpenSSL libraries
RUn apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN apt-get -y install libmariadbclient-dev
RUn apt-get -y install libc++-dev libc++abi-dev