FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# install tools
RUN apt-get -y install git wget curl unzip apt-transport-https ca-certificates software-properties-common

# install compilation-tools
RUN apt-get -y install build-essential clang
RUN apt-get -y install libc++-dev libc++abi-dev

# install cmake
RUN apt-get -y install cmake

# set clang as default compiler
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

# install OpenSSL libraries
RUN apt-get -y install libssl-dev

# install FFMpeg
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libpostproc-dev libavutil-dev libswresample-dev

# install MariaDB libraries
RUN apt-get -y install libmariadbclient-dev

# install ICU-dev
RUN apt-get -y install libicu-dev

RUN echo $(cmake --version)
RUN echo $(cc --version)
RUN echo $(c++ --version)